/*
 * This source file was generated by the Gradle 'init' task
 */
package com.hagen10

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = App2()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
